language: go
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
sudo: required
services: 
  - docker
go:
  - 1.6
install:
  - go get github.com/Masterminds/glide
  - make install-deps
script:
  - make test
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - if [ "$TRAVIS_TAG" ]; then
    TAG="$TRAVIS_TAG" make release;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    make release-dev;
    fi
